# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filter.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(294, 486)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.filterVerLayout = QtWidgets.QVBoxLayout()
        self.filterVerLayout.setObjectName("filterVerLayout")
        self.filterGroupBox = QtWidgets.QGroupBox(Dialog)
        self.filterGroupBox.setObjectName("filterGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.filterGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.disableRadio = QtWidgets.QRadioButton(self.filterGroupBox)
        self.disableRadio.setObjectName("disableRadio")
        self.gridLayout.addWidget(self.disableRadio, 1, 1, 1, 1)
        self.enableRaido = QtWidgets.QRadioButton(self.filterGroupBox)
        self.enableRaido.setObjectName("enableRaido")
        self.gridLayout.addWidget(self.enableRaido, 1, 2, 1, 1)
        self.customLineEdit = QtWidgets.QLineEdit(self.filterGroupBox)
        self.customLineEdit.setObjectName("customLineEdit")
        self.gridLayout.addWidget(self.customLineEdit, 2, 2, 1, 1)
        self.customCheckBox = QtWidgets.QCheckBox(self.filterGroupBox)
        self.customCheckBox.setObjectName("customCheckBox")
        self.gridLayout.addWidget(self.customCheckBox, 2, 1, 1, 1)
        self.filterVerLayout.addWidget(self.filterGroupBox)
        self.intGroupBox = QtWidgets.QGroupBox(Dialog)
        self.intGroupBox.setObjectName("intGroupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.intGroupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ipCheckBox = QtWidgets.QCheckBox(self.intGroupBox)
        self.ipCheckBox.setObjectName("ipCheckBox")
        self.horizontalLayout_3.addWidget(self.ipCheckBox)
        self.icmpCheckBox = QtWidgets.QCheckBox(self.intGroupBox)
        self.icmpCheckBox.setObjectName("icmpCheckBox")
        self.horizontalLayout_3.addWidget(self.icmpCheckBox)
        self.igmpCheckBox = QtWidgets.QCheckBox(self.intGroupBox)
        self.igmpCheckBox.setObjectName("igmpCheckBox")
        self.horizontalLayout_3.addWidget(self.igmpCheckBox)
        self.filterVerLayout.addWidget(self.intGroupBox)
        self.tranGroupBox = QtWidgets.QGroupBox(Dialog)
        self.tranGroupBox.setObjectName("tranGroupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tranGroupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.udpCheckBox = QtWidgets.QCheckBox(self.tranGroupBox)
        self.udpCheckBox.setObjectName("udpCheckBox")
        self.horizontalLayout_2.addWidget(self.udpCheckBox)
        self.tcpCheckBox = QtWidgets.QCheckBox(self.tranGroupBox)
        self.tcpCheckBox.setObjectName("tcpCheckBox")
        self.horizontalLayout_2.addWidget(self.tcpCheckBox)
        self.filterVerLayout.addWidget(self.tranGroupBox)
        self.appGroupBox = QtWidgets.QGroupBox(Dialog)
        self.appGroupBox.setObjectName("appGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.appGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ftpCheckBox = QtWidgets.QCheckBox(self.appGroupBox)
        self.ftpCheckBox.setObjectName("ftpCheckBox")
        self.gridLayout_2.addWidget(self.ftpCheckBox, 0, 0, 1, 1)
        self.telnetCheckBox = QtWidgets.QCheckBox(self.appGroupBox)
        self.telnetCheckBox.setObjectName("telnetCheckBox")
        self.gridLayout_2.addWidget(self.telnetCheckBox, 0, 1, 1, 1)
        self.sshCheckBox = QtWidgets.QCheckBox(self.appGroupBox)
        self.sshCheckBox.setObjectName("sshCheckBox")
        self.gridLayout_2.addWidget(self.sshCheckBox, 0, 2, 1, 1)
        self.dnsCheckBox = QtWidgets.QCheckBox(self.appGroupBox)
        self.dnsCheckBox.setObjectName("dnsCheckBox")
        self.gridLayout_2.addWidget(self.dnsCheckBox, 1, 0, 1, 1)
        self.httpsCheckBox = QtWidgets.QCheckBox(self.appGroupBox)
        self.httpsCheckBox.setObjectName("httpsCheckBox")
        self.gridLayout_2.addWidget(self.httpsCheckBox, 1, 1, 1, 1)
        self.filterVerLayout.addWidget(self.appGroupBox)
        self.verticalLayout_3.addLayout(self.filterVerLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel
                                          | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.filterGroupBox.setTitle(_translate("Dialog", "** Filter**"))
        self.disableRadio.setText(_translate("Dialog", "Disable"))
        self.enableRaido.setText(_translate("Dialog", "Enable"))
        self.customCheckBox.setText(_translate("Dialog", "Custom"))
        self.intGroupBox.setTitle(_translate("Dialog", "Internet Layer"))
        self.ipCheckBox.setText(_translate("Dialog", "IP"))
        self.icmpCheckBox.setText(_translate("Dialog", "ICMP"))
        self.igmpCheckBox.setText(_translate("Dialog", "IGMP"))
        self.tranGroupBox.setTitle(_translate("Dialog", "Transport Layer"))
        self.udpCheckBox.setText(_translate("Dialog", "UDP"))
        self.tcpCheckBox.setText(_translate("Dialog", "TCP"))
        self.appGroupBox.setTitle(_translate("Dialog", "Application Layer"))
        self.ftpCheckBox.setText(_translate("Dialog", "FTP"))
        self.telnetCheckBox.setText(_translate("Dialog", "Telnet"))
        self.sshCheckBox.setText(_translate("Dialog", "SSH"))
        self.dnsCheckBox.setText(_translate("Dialog", "DNS"))
        self.httpsCheckBox.setText(_translate("Dialog", "HTTP(s)"))
