# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(849, 729)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.conciseInfoTable = QtWidgets.QTableWidget(self.splitter)
        self.conciseInfoTable.setShowGrid(False)
        self.conciseInfoTable.setObjectName("conciseInfoTable")
        self.conciseInfoTable.setColumnCount(7)
        self.conciseInfoTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.conciseInfoTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.conciseInfoTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.conciseInfoTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.conciseInfoTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.conciseInfoTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.conciseInfoTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.conciseInfoTable.setHorizontalHeaderItem(6, item)
        self.verboseInfoTab = QtWidgets.QTabWidget(self.splitter)
        self.verboseInfoTab.setObjectName("verboseInfoTab")
        self.linkTab = QtWidgets.QWidget()
        self.linkTab.setObjectName("linkTab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.linkTab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.linkTextEdit = QtWidgets.QPlainTextEdit(self.linkTab)
        self.linkTextEdit.setObjectName("linkTextEdit")
        self.verticalLayout_7.addWidget(self.linkTextEdit)
        self.verboseInfoTab.addTab(self.linkTab, "")
        self.interTab = QtWidgets.QWidget()
        self.interTab.setObjectName("interTab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.interTab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.interTextEdit = QtWidgets.QPlainTextEdit(self.interTab)
        self.interTextEdit.setObjectName("interTextEdit")
        self.verticalLayout_6.addWidget(self.interTextEdit)
        self.verboseInfoTab.addTab(self.interTab, "")
        self.transTab = QtWidgets.QWidget()
        self.transTab.setObjectName("transTab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.transTab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.TransTextEdit = QtWidgets.QPlainTextEdit(self.transTab)
        self.TransTextEdit.setObjectName("TransTextEdit")
        self.verticalLayout_5.addWidget(self.TransTextEdit)
        self.verboseInfoTab.addTab(self.transTab, "")
        self.appTab = QtWidgets.QWidget()
        self.appTab.setObjectName("appTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.appTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.appTextEdit = QtWidgets.QPlainTextEdit(self.appTab)
        self.appTextEdit.setObjectName("appTextEdit")
        self.verticalLayout_4.addWidget(self.appTextEdit)
        self.verboseInfoTab.addTab(self.appTab, "")
        self.decodeInfoTab = QtWidgets.QTabWidget(self.splitter)
        self.decodeInfoTab.setObjectName("decodeInfoTab")
        self.rawTab = QtWidgets.QWidget()
        self.rawTab.setObjectName("rawTab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.rawTab)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.rawTextEdit = QtWidgets.QPlainTextEdit(self.rawTab)
        self.rawTextEdit.setObjectName("rawTextEdit")
        self.verticalLayout_8.addWidget(self.rawTextEdit)
        self.decodeInfoTab.addTab(self.rawTab, "")
        self.hexTab = QtWidgets.QWidget()
        self.hexTab.setObjectName("hexTab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.hexTab)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.hexTextEdit = QtWidgets.QPlainTextEdit(self.hexTab)
        self.hexTextEdit.setObjectName("hexTextEdit")
        self.verticalLayout_9.addWidget(self.hexTextEdit)
        self.decodeInfoTab.addTab(self.hexTab, "")
        self.horizontalLayout_8.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 849, 26))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_export = QtWidgets.QMenu(self.menu_File)
        self.menu_export.setObjectName("menu_export")
        self.menuNetwork_info = QtWidgets.QMenu(self.menu_export)
        self.menuNetwork_info.setObjectName("menuNetwork_info")
        self.menuLAN_info = QtWidgets.QMenu(self.menu_export)
        self.menuLAN_info.setObjectName("menuLAN_info")
        self.menuPackets_info = QtWidgets.QMenu(self.menu_export)
        self.menuPackets_info.setObjectName("menuPackets_info")
        self.menuCapture = QtWidgets.QMenu(self.menubar)
        self.menuCapture.setObjectName("menuCapture")
        self.menuStatistic = QtWidgets.QMenu(self.menubar)
        self.menuStatistic.setObjectName("menuStatistic")
        self.menu_protocol = QtWidgets.QMenu(self.menuStatistic)
        self.menu_protocol.setObjectName("menu_protocol")
        self.menu_length = QtWidgets.QMenu(self.menuStatistic)
        self.menu_length.setObjectName("menu_length")
        self.menu_time = QtWidgets.QMenu(self.menuStatistic)
        self.menu_time.setObjectName("menu_time")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.controlDock = QtWidgets.QDockWidget(MainWindow)
        self.controlDock.setEnabled(True)
        self.controlDock.setFloating(False)
        self.controlDock.setObjectName("controlDock")
        self.controlDockContents = QtWidgets.QWidget()
        self.controlDockContents.setObjectName("controlDockContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(
            self.controlDockContents)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.controlTabManage = QtWidgets.QTabWidget(self.controlDockContents)
        self.controlTabManage.setTabBarAutoHide(False)
        self.controlTabManage.setObjectName("controlTabManage")
        self.networklTab = QtWidgets.QWidget()
        self.networklTab.setObjectName("networklTab")
        self.formLayout = QtWidgets.QFormLayout(self.networklTab)
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(self.networklTab)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole,
                                  self.nameLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(self.networklTab)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole,
                                  self.nameLineEdit)
        self.ipLabel = QtWidgets.QLabel(self.networklTab)
        self.ipLabel.setObjectName("ipLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole,
                                  self.ipLabel)
        self.ipLineEdit = QtWidgets.QLineEdit(self.networklTab)
        self.ipLineEdit.setObjectName("ipLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole,
                                  self.ipLineEdit)
        self.macLabel = QtWidgets.QLabel(self.networklTab)
        self.macLabel.setObjectName("macLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole,
                                  self.macLabel)
        self.macLineEdit = QtWidgets.QLineEdit(self.networklTab)
        self.macLineEdit.setObjectName("macLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole,
                                  self.macLineEdit)
        self.vendorLabel = QtWidgets.QLabel(self.networklTab)
        self.vendorLabel.setObjectName("vendorLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole,
                                  self.vendorLabel)
        self.vendorLineEdit = QtWidgets.QLineEdit(self.networklTab)
        self.vendorLineEdit.setObjectName("vendorLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole,
                                  self.vendorLineEdit)
        self.netmaskLabel = QtWidgets.QLabel(self.networklTab)
        self.netmaskLabel.setObjectName("netmaskLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole,
                                  self.netmaskLabel)
        self.netmaskLineEdit = QtWidgets.QLineEdit(self.networklTab)
        self.netmaskLineEdit.setObjectName("netmaskLineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole,
                                  self.netmaskLineEdit)
        self.gwIpLabel = QtWidgets.QLabel(self.networklTab)
        self.gwIpLabel.setObjectName("gwIpLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole,
                                  self.gwIpLabel)
        self.gwMacLineEdit = QtWidgets.QLineEdit(self.networklTab)
        self.gwMacLineEdit.setObjectName("gwMacLineEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole,
                                  self.gwMacLineEdit)
        self.gwVendorLabel = QtWidgets.QLabel(self.networklTab)
        self.gwVendorLabel.setObjectName("gwVendorLabel")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole,
                                  self.gwVendorLabel)
        self.gwVendorLineEdit = QtWidgets.QLineEdit(self.networklTab)
        self.gwVendorLineEdit.setObjectName("gwVendorLineEdit")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole,
                                  self.gwVendorLineEdit)
        self.refreshButton = QtWidgets.QPushButton(self.networklTab)
        self.refreshButton.setObjectName("refreshButton")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole,
                                  self.refreshButton)
        self.localLabel = QtWidgets.QLabel(self.networklTab)
        self.localLabel.setObjectName("localLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole,
                                  self.localLabel)
        self.gwLabel = QtWidgets.QLabel(self.networklTab)
        self.gwLabel.setObjectName("gwLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole,
                                  self.gwLabel)
        self.gwMacLabel = QtWidgets.QLabel(self.networklTab)
        self.gwMacLabel.setObjectName("gwMacLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole,
                                  self.gwMacLabel)
        self.gwIpLineEdit = QtWidgets.QLineEdit(self.networklTab)
        self.gwIpLineEdit.setObjectName("gwIpLineEdit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole,
                                  self.gwIpLineEdit)
        self.unlockButton = QtWidgets.QPushButton(self.networklTab)
        self.unlockButton.setObjectName("unlockButton")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole,
                                  self.unlockButton)
        self.controlTabManage.addTab(self.networklTab, "")
        self.scanTab = QtWidgets.QWidget()
        self.scanTab.setObjectName("scanTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scanTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.rangeLabel = QtWidgets.QLabel(self.scanTab)
        self.rangeLabel.setObjectName("rangeLabel")
        self.verticalLayout_3.addWidget(self.rangeLabel)
        self.rangeLineEdit = QtWidgets.QLineEdit(self.scanTab)
        self.rangeLineEdit.setObjectName("rangeLineEdit")
        self.verticalLayout_3.addWidget(self.rangeLineEdit)
        self.rangeButton = QtWidgets.QPushButton(self.scanTab)
        self.rangeButton.setObjectName("rangeButton")
        self.verticalLayout_3.addWidget(self.rangeButton)
        self.maskLabel = QtWidgets.QLabel(self.scanTab)
        self.maskLabel.setObjectName("maskLabel")
        self.verticalLayout_3.addWidget(self.maskLabel)
        self.maskLineEdit = QtWidgets.QLineEdit(self.scanTab)
        self.maskLineEdit.setObjectName("maskLineEdit")
        self.verticalLayout_3.addWidget(self.maskLineEdit)
        self.maskButton = QtWidgets.QPushButton(self.scanTab)
        self.maskButton.setObjectName("maskButton")
        self.verticalLayout_3.addWidget(self.maskButton)
        self.controlTabManage.addTab(self.scanTab, "")
        self.filterTab = QtWidgets.QWidget()
        self.filterTab.setObjectName("filterTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.filterTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.intGroupBox = QtWidgets.QGroupBox(self.filterTab)
        self.intGroupBox.setObjectName("intGroupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.intGroupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ipv4CheckBox = QtWidgets.QCheckBox(self.intGroupBox)
        self.ipv4CheckBox.setObjectName("ipv4CheckBox")
        self.horizontalLayout_3.addWidget(self.ipv4CheckBox)
        self.icmpCheckBox = QtWidgets.QCheckBox(self.intGroupBox)
        self.icmpCheckBox.setObjectName("icmpCheckBox")
        self.horizontalLayout_3.addWidget(self.icmpCheckBox)
        self.igmpCheckBox = QtWidgets.QCheckBox(self.intGroupBox)
        self.igmpCheckBox.setObjectName("igmpCheckBox")
        self.horizontalLayout_3.addWidget(self.igmpCheckBox)
        self.verticalLayout_2.addWidget(self.intGroupBox)
        self.TranGroupBox = QtWidgets.QGroupBox(self.filterTab)
        self.TranGroupBox.setObjectName("TranGroupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.TranGroupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.udpCheckBox = QtWidgets.QCheckBox(self.TranGroupBox)
        self.udpCheckBox.setObjectName("udpCheckBox")
        self.horizontalLayout_4.addWidget(self.udpCheckBox)
        self.tcpCheckBox = QtWidgets.QCheckBox(self.TranGroupBox)
        self.tcpCheckBox.setObjectName("tcpCheckBox")
        self.horizontalLayout_4.addWidget(self.tcpCheckBox)
        self.verticalLayout_2.addWidget(self.TranGroupBox)
        self.appGroupBox = QtWidgets.QGroupBox(self.filterTab)
        self.appGroupBox.setObjectName("appGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.appGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.ftpCheckBox = QtWidgets.QCheckBox(self.appGroupBox)
        self.ftpCheckBox.setObjectName("ftpCheckBox")
        self.gridLayout.addWidget(self.ftpCheckBox, 0, 1, 1, 1)
        self.telCheckBox = QtWidgets.QCheckBox(self.appGroupBox)
        self.telCheckBox.setObjectName("telCheckBox")
        self.gridLayout.addWidget(self.telCheckBox, 0, 2, 1, 1)
        self.sshCheckBox = QtWidgets.QCheckBox(self.appGroupBox)
        self.sshCheckBox.setObjectName("sshCheckBox")
        self.gridLayout.addWidget(self.sshCheckBox, 0, 4, 1, 1)
        self.dnsCheckBox = QtWidgets.QCheckBox(self.appGroupBox)
        self.dnsCheckBox.setObjectName("dnsCheckBox")
        self.gridLayout.addWidget(self.dnsCheckBox, 2, 1, 1, 1)
        self.httpCheckBox = QtWidgets.QCheckBox(self.appGroupBox)
        self.httpCheckBox.setObjectName("httpCheckBox")
        self.gridLayout.addWidget(self.httpCheckBox, 2, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.appGroupBox)
        self.optGroupBox = QtWidgets.QGroupBox(self.filterTab)
        self.optGroupBox.setObjectName("optGroupBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.optGroupBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.allRadioButton = QtWidgets.QRadioButton(self.optGroupBox)
        self.allRadioButton.setObjectName("allRadioButton")
        self.horizontalLayout_5.addWidget(self.allRadioButton)
        self.verticalLayout_2.addWidget(self.optGroupBox)
        self.controlTabManage.addTab(self.filterTab, "")
        self.searchTab = QtWidgets.QWidget()
        self.searchTab.setObjectName("searchTab")
        self.formLayout_4 = QtWidgets.QFormLayout(self.searchTab)
        self.formLayout_4.setObjectName("formLayout_4")
        self.searchLabel = QtWidgets.QLabel(self.searchTab)
        self.searchLabel.setObjectName("searchLabel")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole,
                                    self.searchLabel)
        self.searchLineEdit = QtWidgets.QLineEdit(self.searchTab)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole,
                                    self.searchLineEdit)
        self.searchButton = QtWidgets.QPushButton(self.searchTab)
        self.searchButton.setObjectName("searchButton")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole,
                                    self.searchButton)
        self.controlTabManage.addTab(self.searchTab, "")
        self.ipinfoTab = QtWidgets.QWidget()
        self.ipinfoTab.setObjectName("ipinfoTab")
        self.formLayout_3 = QtWidgets.QFormLayout(self.ipinfoTab)
        self.formLayout_3.setObjectName("formLayout_3")
        self.sipLabel = QtWidgets.QLabel(self.ipinfoTab)
        self.sipLabel.setObjectName("sipLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole,
                                    self.sipLabel)
        self.sipLineEdit = QtWidgets.QLineEdit(self.ipinfoTab)
        self.sipLineEdit.setObjectName("sipLineEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole,
                                    self.sipLineEdit)
        self.sipTextEdit = QtWidgets.QTextEdit(self.ipinfoTab)
        self.sipTextEdit.setObjectName("sipTextEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.SpanningRole,
                                    self.sipTextEdit)
        self.sipButton = QtWidgets.QPushButton(self.ipinfoTab)
        self.sipButton.setObjectName("sipButton")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole,
                                    self.sipButton)
        self.controlTabManage.addTab(self.ipinfoTab, "")
        self.horizontalLayout_2.addWidget(self.controlTabManage)
        self.controlDock.setWidget(self.controlDockContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.controlDock)
        self.scanDock = QtWidgets.QDockWidget(MainWindow)
        self.scanDock.setObjectName("scanDock")
        self.scanDockContents = QtWidgets.QWidget()
        self.scanDockContents.setObjectName("scanDockContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scanDockContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nodeListWidget = QtWidgets.QListWidget(self.scanDockContents)
        self.nodeListWidget.setObjectName("nodeListWidget")
        self.verticalLayout.addWidget(self.nodeListWidget)
        self.scanProgressBar = QtWidgets.QProgressBar(self.scanDockContents)
        self.scanProgressBar.setProperty("value", 24)
        self.scanProgressBar.setObjectName("scanProgressBar")
        self.verticalLayout.addWidget(self.scanProgressBar)
        self.analysisPushButton = QtWidgets.QPushButton(self.scanDockContents)
        self.analysisPushButton.setObjectName("analysisPushButton")
        self.verticalLayout.addWidget(self.analysisPushButton)
        self.stopPushButton = QtWidgets.QPushButton(self.scanDockContents)
        self.stopPushButton.setObjectName("stopPushButton")
        self.verticalLayout.addWidget(self.stopPushButton)
        self.scanDock.setWidget(self.scanDockContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.scanDock)
        self.action_Save = QtWidgets.QAction(MainWindow)
        self.action_Save.setObjectName("action_Save")
        self.action_Open = QtWidgets.QAction(MainWindow)
        self.action_Open.setObjectName("action_Open")
        self.action_Export = QtWidgets.QAction(MainWindow)
        self.action_Export.setObjectName("action_Export")
        self.actionExportCSV = QtWidgets.QAction(MainWindow)
        self.actionExportCSV.setObjectName("actionExportCSV")
        self.actionExportJSON = QtWidgets.QAction(MainWindow)
        self.actionExportJSON.setObjectName("actionExportJSON")
        self.actionExportPlain = QtWidgets.QAction(MainWindow)
        self.actionExportPlain.setObjectName("actionExportPlain")
        self.actionLANCSV = QtWidgets.QAction(MainWindow)
        self.actionLANCSV.setObjectName("actionLANCSV")
        self.actionLANJSON = QtWidgets.QAction(MainWindow)
        self.actionLANJSON.setObjectName("actionLANJSON")
        self.actionLANPlain = QtWidgets.QAction(MainWindow)
        self.actionLANPlain.setObjectName("actionLANPlain")
        self.actionPktCSV = QtWidgets.QAction(MainWindow)
        self.actionPktCSV.setObjectName("actionPktCSV")
        self.actionPktJSON = QtWidgets.QAction(MainWindow)
        self.actionPktJSON.setObjectName("actionPktJSON")
        self.actionPktPlain = QtWidgets.QAction(MainWindow)
        self.actionPktPlain.setObjectName("actionPktPlain")
        self.action_Start = QtWidgets.QAction(MainWindow)
        self.action_Start.setObjectName("action_Start")
        self.actionSto_p = QtWidgets.QAction(MainWindow)
        self.actionSto_p.setObjectName("actionSto_p")
        self.action_restart = QtWidgets.QAction(MainWindow)
        self.action_restart.setObjectName("action_restart")
        self.action_ProBar = QtWidgets.QAction(MainWindow)
        self.action_ProBar.setObjectName("action_ProBar")
        self.action_ProHbar = QtWidgets.QAction(MainWindow)
        self.action_ProHbar.setObjectName("action_ProHbar")
        self.action_ProPie = QtWidgets.QAction(MainWindow)
        self.action_ProPie.setObjectName("action_ProPie")
        self.action_LenBar = QtWidgets.QAction(MainWindow)
        self.action_LenBar.setObjectName("action_LenBar")
        self.action_LenHbar = QtWidgets.QAction(MainWindow)
        self.action_LenHbar.setObjectName("action_LenHbar")
        self.action_LenPie = QtWidgets.QAction(MainWindow)
        self.action_LenPie.setObjectName("action_LenPie")
        self.action_TimeBar = QtWidgets.QAction(MainWindow)
        self.action_TimeBar.setObjectName("action_TimeBar")
        self.action_TimeHbar = QtWidgets.QAction(MainWindow)
        self.action_TimeHbar.setObjectName("action_TimeHbar")
        self.action_TimePie = QtWidgets.QAction(MainWindow)
        self.action_TimePie.setObjectName("action_TimePie")
        self.action_Stop = QtWidgets.QAction(MainWindow)
        self.action_Stop.setObjectName("action_Stop")
        self.action_Restart = QtWidgets.QAction(MainWindow)
        self.action_Restart.setObjectName("action_Restart")
        self.action_Help = QtWidgets.QAction(MainWindow)
        self.action_Help.setObjectName("action_Help")
        self.action_Author = QtWidgets.QAction(MainWindow)
        self.action_Author.setObjectName("action_Author")
        self.action_close = QtWidgets.QAction(MainWindow)
        self.action_close.setObjectName("action_close")
        self.action_rank = QtWidgets.QAction(MainWindow)
        self.action_rank.setObjectName("action_rank")
        self.action_Rank = QtWidgets.QAction(MainWindow)
        self.action_Rank.setObjectName("action_Rank")
        self.menuNetwork_info.addAction(self.actionExportCSV)
        self.menuNetwork_info.addAction(self.actionExportJSON)
        self.menuNetwork_info.addAction(self.actionExportPlain)
        self.menuLAN_info.addAction(self.actionLANCSV)
        self.menuLAN_info.addAction(self.actionLANJSON)
        self.menuLAN_info.addAction(self.actionLANPlain)
        self.menuPackets_info.addAction(self.actionPktCSV)
        self.menuPackets_info.addAction(self.actionPktJSON)
        self.menuPackets_info.addAction(self.actionPktPlain)
        self.menu_export.addAction(self.menuNetwork_info.menuAction())
        self.menu_export.addAction(self.menuLAN_info.menuAction())
        self.menu_export.addAction(self.menuPackets_info.menuAction())
        self.menu_File.addAction(self.action_Save)
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.menu_export.menuAction())
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_close)
        self.menuCapture.addAction(self.action_Start)
        self.menuCapture.addSeparator()
        self.menuCapture.addAction(self.action_Stop)
        self.menuCapture.addSeparator()
        self.menuCapture.addAction(self.action_Restart)
        self.menu_protocol.addAction(self.action_ProBar)
        self.menu_protocol.addAction(self.action_ProHbar)
        self.menu_protocol.addAction(self.action_ProPie)
        self.menu_length.addAction(self.action_LenBar)
        self.menu_length.addAction(self.action_LenHbar)
        self.menu_length.addAction(self.action_LenPie)
        self.menu_time.addAction(self.action_TimeBar)
        self.menu_time.addAction(self.action_TimeHbar)
        self.menu_time.addAction(self.action_TimePie)
        self.menuStatistic.addAction(self.menu_protocol.menuAction())
        self.menuStatistic.addAction(self.menu_length.menuAction())
        self.menuStatistic.addAction(self.menu_time.menuAction())
        self.menuAbout.addAction(self.action_Help)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.action_Author)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.action_Rank)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuCapture.menuAction())
        self.menubar.addAction(self.menuStatistic.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.verboseInfoTab.setCurrentIndex(0)
        self.decodeInfoTab.setCurrentIndex(0)
        self.controlTabManage.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.conciseInfoTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "No."))
        item = self.conciseInfoTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Time"))
        item = self.conciseInfoTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Source"))
        item = self.conciseInfoTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Destination"))
        item = self.conciseInfoTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Protocol"))
        item = self.conciseInfoTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Length"))
        item = self.conciseInfoTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Info"))
        self.verboseInfoTab.setTabText(
            self.verboseInfoTab.indexOf(self.linkTab),
            _translate("MainWindow", "link"))
        self.verboseInfoTab.setTabText(
            self.verboseInfoTab.indexOf(self.interTab),
            _translate("MainWindow", "internet"))
        self.verboseInfoTab.setTabText(
            self.verboseInfoTab.indexOf(self.transTab),
            _translate("MainWindow", "transport"))
        self.verboseInfoTab.setTabText(
            self.verboseInfoTab.indexOf(self.appTab),
            _translate("MainWindow", "application"))
        self.decodeInfoTab.setTabText(
            self.decodeInfoTab.indexOf(self.rawTab),
            _translate("MainWindow", "raw binary"))
        self.decodeInfoTab.setTabText(
            self.decodeInfoTab.indexOf(self.hexTab),
            _translate("MainWindow", "hex decode"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_export.setTitle(_translate("MainWindow", "&export"))
        self.menuNetwork_info.setTitle(
            _translate("MainWindow", "&network info"))
        self.menuLAN_info.setTitle(_translate("MainWindow", "&LAN info"))
        self.menuPackets_info.setTitle(
            _translate("MainWindow", "&packets info"))
        self.menuCapture.setTitle(_translate("MainWindow", "&Capture"))
        self.menuStatistic.setTitle(_translate("MainWindow", "&Statistic"))
        self.menu_protocol.setTitle(_translate("MainWindow", "&protocol"))
        self.menu_length.setTitle(_translate("MainWindow", "&length"))
        self.menu_time.setTitle(_translate("MainWindow", "&time"))
        self.menuAbout.setTitle(_translate("MainWindow", "&About"))
        self.controlDock.setWindowTitle(
            _translate("MainWindow", "Control Panel"))
        self.nameLabel.setText(_translate("MainWindow", "Name"))
        self.ipLabel.setText(_translate("MainWindow", "IP"))
        self.macLabel.setText(_translate("MainWindow", "Mac"))
        self.vendorLabel.setText(_translate("MainWindow", "Vendor"))
        self.netmaskLabel.setText(_translate("MainWindow", "Netmask"))
        self.gwIpLabel.setText(_translate("MainWindow", "IP"))
        self.gwVendorLabel.setText(_translate("MainWindow", "Vendor"))
        self.refreshButton.setText(_translate("MainWindow", "refresh"))
        self.localLabel.setText(_translate("MainWindow", ">>> Local"))
        self.gwLabel.setText(_translate("MainWindow", ">>> Gateway"))
        self.gwMacLabel.setText(_translate("MainWindow", "Mac"))
        self.unlockButton.setText(_translate("MainWindow", "unlock"))
        self.controlTabManage.setTabText(
            self.controlTabManage.indexOf(self.networklTab),
            _translate("MainWindow", "network"))
        self.rangeLabel.setText(_translate("MainWindow", "Range"))
        self.rangeButton.setText(_translate("MainWindow", "range scan"))
        self.maskLabel.setText(_translate("MainWindow", "Mask"))
        self.maskButton.setText(_translate("MainWindow", "mask scan"))
        self.controlTabManage.setTabText(
            self.controlTabManage.indexOf(self.scanTab),
            _translate("MainWindow", "scan"))
        self.intGroupBox.setTitle(_translate("MainWindow", "Internet Layer"))
        self.ipv4CheckBox.setText(_translate("MainWindow", "IPv4"))
        self.icmpCheckBox.setText(_translate("MainWindow", "ICMP"))
        self.igmpCheckBox.setText(_translate("MainWindow", "IGMP"))
        self.TranGroupBox.setTitle(_translate("MainWindow", "Transport Layer"))
        self.udpCheckBox.setText(_translate("MainWindow", "UDP"))
        self.tcpCheckBox.setText(_translate("MainWindow", "TCP"))
        self.appGroupBox.setTitle(
            _translate("MainWindow", "Application Layer"))
        self.ftpCheckBox.setText(_translate("MainWindow", "FTP"))
        self.telCheckBox.setText(_translate("MainWindow", "Telnet"))
        self.sshCheckBox.setText(_translate("MainWindow", "SSH"))
        self.dnsCheckBox.setText(_translate("MainWindow", "DNS"))
        self.httpCheckBox.setText(_translate("MainWindow", "HTTP(s)"))
        self.optGroupBox.setTitle(_translate("MainWindow", "Option"))
        self.allRadioButton.setText(_translate("MainWindow", "all "))
        self.controlTabManage.setTabText(
            self.controlTabManage.indexOf(self.filterTab),
            _translate("MainWindow", "filter"))
        self.searchLabel.setText(_translate("MainWindow", "Search"))
        self.searchButton.setText(_translate("MainWindow", "search"))
        self.controlTabManage.setTabText(
            self.controlTabManage.indexOf(self.searchTab),
            _translate("MainWindow", "search"))
        self.sipLabel.setText(_translate("MainWindow", "search IP"))
        self.sipButton.setText(_translate("MainWindow", "seach"))
        self.controlTabManage.setTabText(
            self.controlTabManage.indexOf(self.ipinfoTab),
            _translate("MainWindow", "ipinfo"))
        self.scanDock.setWindowTitle(_translate("MainWindow", "Scan Panel"))
        self.analysisPushButton.setText(_translate("MainWindow", "analysis"))
        self.stopPushButton.setText(_translate("MainWindow", "stop"))
        self.action_Save.setText(_translate("MainWindow", "&save"))
        self.action_Open.setText(_translate("MainWindow", "&open"))
        self.action_Export.setText(_translate("MainWindow", "&Export"))
        self.actionExportCSV.setText(_translate("MainWindow", "&CSV"))
        self.actionExportJSON.setText(_translate("MainWindow", "&JSON"))
        self.actionExportPlain.setText(_translate("MainWindow", "&plain text"))
        self.actionLANCSV.setText(_translate("MainWindow", "CSV"))
        self.actionLANJSON.setText(_translate("MainWindow", "JSON"))
        self.actionLANPlain.setText(_translate("MainWindow", "plain text"))
        self.actionPktCSV.setText(_translate("MainWindow", "CSV"))
        self.actionPktJSON.setText(_translate("MainWindow", "JSON"))
        self.actionPktPlain.setText(_translate("MainWindow", "plain text"))
        self.action_Start.setText(_translate("MainWindow", "&start"))
        self.actionSto_p.setText(_translate("MainWindow", "sto&p"))
        self.action_restart.setText(_translate("MainWindow", "&restart"))
        self.action_ProBar.setText(_translate("MainWindow", "&bar"))
        self.action_ProHbar.setText(_translate("MainWindow", "&hbar"))
        self.action_ProPie.setText(_translate("MainWindow", "&pie"))
        self.action_LenBar.setText(_translate("MainWindow", "&bar"))
        self.action_LenHbar.setText(_translate("MainWindow", "&hbar"))
        self.action_LenPie.setText(_translate("MainWindow", "&pie"))
        self.action_TimeBar.setText(_translate("MainWindow", "&bar"))
        self.action_TimeHbar.setText(_translate("MainWindow", "&hbar"))
        self.action_TimePie.setText(_translate("MainWindow", "&pie"))
        self.action_Stop.setText(_translate("MainWindow", "sto&p"))
        self.action_Restart.setText(_translate("MainWindow", "&restart"))
        self.action_Help.setText(_translate("MainWindow", "&help"))
        self.action_Author.setText(_translate("MainWindow", "&author"))
        self.action_close.setText(_translate("MainWindow", "&close"))
        self.action_close.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.action_rank.setText(_translate("MainWindow", "&rank"))
        self.action_Rank.setText(_translate("MainWindow", "&rank"))
